framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        failure_transport: failed

        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    use_notify: true
                    check_delayed_interval: 60000
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            failed: 'doctrine://default?queue_name=failed'

        routing:
            App\Message\GenerateImageMessage: async

        buses:
            messenger.bus.default:
                middleware:
                    - doctrine_transaction

when@test:
    framework:
        messenger:
            transports:
                async: 'in-memory://'
